arenadata/gpbackup

backup/data.go, backup/data_test.go, end_to_end/end_to_end_suite_test.go
backupDataForAllTables function used to attempt to acquire AccessShareLock on foreign tables. This behavior is fixed by
skipping lock acquisition not only for main worker thread (worker 0) but also for the tables, that don't require data
backup (there is no need to acquire locks on external tables in non-main threads as well).
Gpbackup flow implies, that before starting backup of tables' data, it performs their metadata backup. For this, at the very beginning gpbackup acquires AccessShareLock for all the regular tables (relkind='r'), that are going to be backed up. Only after that  list of tables for which metadata should be backed up is extended with foreign tables.
However when gpbackup starts to backup data of the tables, the list still contains foreign tables. backupDataForAllTables …
=> ADBDEV-1714 Avoid lock acquisition for foreign tables

backup/data_test.go, go.mod, go.sum, helper/backup_helper.go, helper/backup_helper_pipes.go, helper/helper.go, helper/restore_helper.go, integration/helper_test.go, options/flag.go, restore/data_test.go, utils/compression.go, utils/compression_test.go, utils/util.go, utils/util_test.go
Support ZSTD compression type in backup, restore, and helper modules.
https://pkg.go.dev/github.com/klauspost/compress/zstd is used as the provider of ZSTD implementation in `backup_helper`.
Add test cases for `zstd` compression type.
=> ADBDEV-1886. Implement ZSTD compression support

backup/backup.go, backup/data_test.go, backup/validate.go, backup/wrappers.go, go.mod, go.sum, helper/backup_helper.go, helper/backup_helper_pipes.go, helper/helper.go, helper/restore_helper.go, history/history.go, integration/helper_test.go, options/flag.go, report/report_test.go, restore/data_test.go, restore/wrappers.go, utils/compression.go, utils/compression_test.go, utils/util.go, utils/util_test.go
This PR duplicates https://github.com/arenadata/gpbackup/pull/2 for a different target branch (`arenadata/master`).
Add a flag to set compression type. `gzip` is the only currently supported value. To disable compression, `--no-compression` or `--compression-level 0` are to be set. `gzip` is also the default value for this parameter.
In `helper`, introduce `backup_helper_pipes.go`. This defines wrappers for buffer writers encapsulating various compression types (currently "no compression" and "gzip"). This allows to drop (somewhat) complex `Writer` closure algorithm in `backup_helper.go`.
Update `helper_test` and `compression_test` according to new changes.
Add support for `zstd` compression type. Update tests and run option descriptions accordingly.
=> ADBDEV-1731. Implement `zstd` compression support

arenadata/arenadata_helper.go, report/report.go, report/report_test.go
Add helper functions and slightly refactor main code in order to support arenadata version suffix + add the appropriate tests
(e.g. `gpbackup version + '_' + arenadata release + ('+' + gpbackup build)`)
Since now this fork only supports the following scenarios:
1. Backup with pivotal gpbackup build, restore with arenadata build
2. Backup with arenadata build, restore with arenadata build
=> ADBDEV-1953 - Handle arenadata suffix in version

arenadata/Dockerfile, arenadata/README.md, arenadata/arenadata_helper.go, arenadata/run_gpbackup_tests.bash, report/report.go, report/report_test.go
We need to implement several improvements to make it possible to run
upstream test suite on top of our fork:
1. We need a separate script that runs the test suite inside a container with gpdb demo cluster
2. We need modification of version processing logic to use our own versioning system with patch number in arenadata-suffix.
=> ADBDEV-1918 Implement scripts ti run gpbackup tests

backup/validate.go, backup/validate_test.go
There is a potential situation, when data in a partition table is backed up and restored twice:
```
adb=# CREATE TABLE rank25 (id int, rank int, year int, gender 
char(1), count int)
DISTRIBUTED BY (id)
PARTITION BY RANGE (year)
( START (2006) END (2016) EVERY (1), 
DEFAULT PARTITION extra );
adb=# insert into rank25 values (1, 1, 2006, 'M', 1) 
adb=# select * from rank25;
id | rank | year | gender | count 
----+------+------+--------+-------
1 |    1 | 2006 | M      |     1
(1 row)
adb=# select * from public.rank25_1_prt_2;
id | rank | year | gender | count 
----+------+------+--------+-------
1 |    1 | 2006 | M      |     1
(1 row)
adb=# create database kek;
$ gpbackup --dbname adb --include-table public.rank25 --include-table public.rank25_1_prt_2
...
20210910:09:56:10 …
```
=> ADBDEV-2049 Prohibit inclusion of leaf partitions without --leaf-partition-data

backup/backup.go, backup/dependencies.go, backup/wrappers.go, end_to_end/end_to_end_suite_test.go
```
CREATE TABLE mytable (
id integer PRIMARY KEY,
name text,
fromdate timestamp with time zone NOT NULL
);
CREATE OR REPLACE FUNCTION myfunc(arg mytable[]) RETURNS void
LANGUAGE plpgsql IMMUTABLE STRICT AS
$$DECLARE
t mytable;
BEGIN
FOREACH t IN ARRAY arg LOOP
RAISE NOTICE 'id = %', t.id;
END LOOP;
END;$$;
```
If we create a function that recieves a set of rows as parameter, then try to backup and restore it, we can get an error:
```
LANGUAGE plpgsql NO SQL IMMUTABLE STRICT; Error was: ERROR: type public.mytable[] does not exist (SQLSTATE 42704)
```
The error says that we can't create a table which recieves a set of rows of an unknown table. That error occurs because gpbackup writes DDL of functions former than that of tables. 
Actually, gpbackup tries to resolve dependencies, but this …
=> ADBDEV-2901 Fix order of restoring metadata 

arenadata/run_gpbackup_tests.bash
- go binary was bumped to 1.20.5
- directory to store go binaries was changed: instead of ~/go (GOPATH) directory /opt/go uses to untar go archive. It's done due to compilation errors (`unkeyed fields at composite literals`, here is a link to stackoverflow: https://stackoverflow.com/questions/54548441/composite-literal-uses-unkeyed-fields) occured at unit-test stage (restore tets), after merging with upstream code, like:
```bash
#> PATH=$PATH:~/go/bin GOPATH=~/go ginkgo restore
Failed to compile restore:
./wrappers_test.go:168:54: github.com/greenplum-db/gpbackup/history.RestorePlanEntry struct literal uses unkeyed fields
./wrappers_test.go:194:54: github.com/greenplum-db/gpbackup/history.RestorePlanEntry struct literal uses unkeyed fields
```
The error occurs at next (strange) condition: …
=> arenadata: modify build scripts

end_to_end/end_to_end_suite_test.go, filepath/filepath.go, filepath/filepath_test.go, options/flag.go, restore/restore.go
New option allows to create report files in directory different from --backup-dir.
Main code changes were made for filepath class. Now it takes new option as deafult path for reports with fallback to content dir.
Unit and end_to_end tests were updated to show mentioned behavior.
______________
Internal specification:
https://wiki.adsw.io/books/adb/page/gprestore-custom-reports-folder
=> Implement --report-dir option for gprestore

backup/queries_relations.go, end_to_end/end_to_end_suite_test.go, end_to_end/filtered_test.go
Exclude subpartitions for given root partition in leaf-partition-data mode
gpbackup with the --leaf-partition-data and --exclude <root_partition> options
adds leaf partitions to the recovery plan, but the root partition is not
included in the schema creation script and gprestore fails with an error.
The solution is to exclude all leaf partitions for a given root partition
in leaf-partition-data mode.
The first test checks that if root partition exclusion and the
leaf-partition-data option are specified, then leaf partitions
should not be included in the restore.
The second test checks that if leaf partition exclusion and the
leaf-partition-data option are specified, then the patch does not
change the behavior: only this leaf partition is excluded from the backup.
The third test checks …
=> ADBDEV-4198: Exclude subpartitions for given root partition in leaf-partition-data mode

plugins/null_plugin.bash
The plugin just writes all the data to /dev/null. This plugin is supposed to be
used instead of ddboost plugin to check whether gpdb and gpbackup pipeline are
the bottleneck of backup procedure on the given cluster.
=> ADBDEV-4512: Add plugin that writes all the data to /dev/null

backup/backup.go, backup/wrappers.go, end_to_end/end_to_end_suite_test.go, integration/wrappers_test.go
Fix backup statistics for leaf partitions
gpbackup does not backup statistics for leaf partitions with leaf-partition-data option
This patch solves the problem by backuping statistics for all specified
tables, including leaf partitions, and not just root partitions.
The test for this patch is based on the test for the 85384fadf774560b87df4d30792644b87069583e.
And, as stated in that patch, it removes the unnecessary
condition when comparing the number of statistics.
=> ADBDEV-4377: Fix backup statistics for leaf partitions

integration/wrappers_test.go
Fix backup table ordering tests
Upstream commit 7833212 removed the ExpandIncludesForPartitions function,
but it continued to be used in our tests in commit 1ddc17e. Because of this,
integration tests could not run and would throw compilation errors.
```
Failed to compile integration:
./wrappers_test.go:168:16: opts.ExpandIncludesForPartitions undefined (type *options.Options has no field or method ExpandIncludesForPartitions)
./wrappers_test.go:184:16: opts.ExpandIncludesForPartitions undefined (type *options.Options has no field or method ExpandIncludesForPartitions)
```
I corrected our tests so that there were no compilation errors
and they passed successfully.
=> ADBDEV-4740: Fix backup table ordering tests

.github/workflows/build_and_unit_test.yml, arenadata/run_gpbackup_tests.bash
Run gpbackup unit-tests on github actions
1) Fix golang version to run [gpbackup unit tests](https://github.com/arenadata/gpbackup/blob/master/.github/workflows/build_and_unit_test.yml) on github actions
2) Remove unit test run from our regression [test suite](https://github.com/arenadata/gpbackup/blob/85384fadf774560b87df4d30792644b87069583e/arenadata/run_gpbackup_tests.bash#L19C48-L19C86)
The failed test will be fixed, when https://github.com/arenadata/gpbackup/pull/49 will be done.
=> ADBDEV-4597: Run gpbackup unit-tests on github actions

backup/queries_functions.go, backup/queries_relations.go
gpbackup used pg_partition and pg_partition_rule to select partitions for gpdb6
and prior, but gpdb7 ditched them. This patch adds a new query for gpdb7 which
uses pg_partition_root. Also, gpdb7 complains on the query from GetExtension
saying that it's ambiguous. This patch also fixes it
=> ADBDEV-4534 Implement gpdb 7 support for gpbackup ordering patch

backup/backup.go, backup/queries_functions.go, backup/wrappers.go, end_to_end/end_to_end_suite_test.go
Rework patch 11da7e0 that solves function-table type dependency issue
Patch 0c3ab91 backups functions before tables unconditionally.
In this case gprestore can not restore functions, that depend on tables
by arguments or return types.
This patch solves this issue by backup independent functions before
tables and dependent functions after.
Test is taken from 11da7e0
=> ADBDEV-4738: Rework patch that solves function-table type dependency issue

backup/data.go, integration/data_backup_test.go
gpbackup does not use shared snapshot for first table in worker processes
gpbackup:
1) [creates](https://github.com/arenadata/gpbackup/blob/7d7f7d565ae81c2fe2fe34e59820ce3b84bde081/backup/wrappers.go#L62) a connection pool
2) [opens](https://github.com/arenadata/gpbackup/blob/7d7f7d565ae81c2fe2fe34e59820ce3b84bde081/backup/wrappers.go#L70) transactions for each connection
3) [takes and exports](https://github.com/arenadata/gpbackup/blob/7d7f7d565ae81c2fe2fe34e59820ce3b84bde081/backup/wrappers.go#L72) a shared snapshot of the first connection
4) [spawns](https://github.com/arenadata/gpbackup/blob/7d7f7d565ae81c2fe2fe34e59820ce3b84bde081/backup/data.go#L173) worker processes for all connections (except the first one),
which perform the following actions:
a) if the transaction is not yet …
=> ADBDEV-4533: gpbackup does not use shared snapshot for first table in worker processes

arenadata/Dockerfile, arenadata/README.md, arenadata/run_gpbackup_tests.bash
Adopt test scripts to run on 7x
This patch adds new commands to already existing files, so they can be used with
7x image.
Base image name in Dockerfile is parametrized now. The behavior is the same if
there is no value passed.
Bash script extended with locale installation. gpbackup contains 7x specific
tests with de_DE locale.
README was extended with additional instructions to run tests. Please use new
instructions to test this patch locally.
=> Adopt test scripts to run on 7x

restore/parallel.go, utils/progress_bar.go
These commits are clean cherry-pick of upstream one (see hashes in the 
commit description). Initially the 1st one found on CI and the 2nd on build 
with race detector.
The 1st commit:
rying to assign channels to the map, and spin up a go routine that uses
the map in the same loop can result in the following panic at run time.
`fatal error: concurrent map read and map write`
This can also be detected using golang's race condition detector
The 2nd commit:
Our progress bar is not concurrency safe since many go routines may be
attempting to modify the values at the same time. Add a mutex to be used
by the progress bar for safe incrementing in go routines.
Without this fix the following issue is found by the golang race
detector
=> ADBDEV-5112 Fix races detected in parallel metadata restore

backup/data.go, backup/predata_relations.go, backup/queries_relations.go, backup/queries_shared.go, backup/queries_table_defs.go, backup/wrappers.go, end_to_end/end_to_end_suite_test.go, end_to_end/resources/test_ext1--1.0.sql
Make it possible to backup/restore extension configuration tables.
This patch adds support for extension configuration tables to gpbackup. The
extension script can specify tables that need to be backuped/restored using the
standard function pg_catalog.pg_extension_config_dump. As a result, gpbackup
will include the data of the specified tables (but not their definition) in the
backup. If the second argument to the pg_catalog.pg_extension_config_dump
function is an empty string, then gpbackup will dump the entire contents of the
table. A non-empty string in the second argument of the
pg_catalog.pg_extension_config_dump function means a WHERE clause that filters
out the data to be dumped. gpdb versions earlier than 7 do not support the
IGNORE EXTERNAL PARTITIONS option for the COPY ( query …
=> ADBDEV-5189: Make it possible to backup/restore extension config tables

end_to_end/end_to_end_suite_test.go, restore/data.go
Fix gprestore hang on errors with on-error-continue option when resize-restore
gprestore did not correctly handle the on-error-continue option when
resize-restore. Errors during restore could cause restore helpers to freeze.
This patch adds the creation of skip files in case of errors, as well as error
checking on segments during resize-restore, as is already done with
single-data-file.
=> ADBDEV-5321: Fix gprestore hang on errors with on-error-continue option when resize-restore

backup/backup.go, backup/dependencies.go, backup/queries_functions.go, backup/wrappers.go, end_to_end/end_to_end_suite_test.go, integration/dependency_queries_test.go
there are complex logic to handle object dependencies in GetDependencies
function. This logic starts from non-internal dependencies (e.g. with
namespaces) and enrich them by up to two levels of internal dependencies.
E.g. some function depends on composite type and this type depends
on a user table. But sometimes it's not enough, e.g. in case of
function argument is an array of user composite types. In this case
dependency chain is function-array_of_type-type-relation:
```
classid  |     objid      |  refclassid  |   refobjid   | deptype
----------+----------------+--------------+--------------+---------
pg_type  | some_table     | pg_class     | some_table   | i
pg_type  | some_table[]   | pg_type      | some_table   | i
pg_class | some_table     | pg_namespace | public       | n
pg_proc …
```
=> fix dependency handling for functions

helper/helper_suite_test.go, helper/helper_test.go, helper/restore_helper.go
```
Fix restoring with subset and --on-error-continue together
Subset restore API is incompatibilite with enabled "--on-error-continue" flag.
When some error is occured at reading data from file, plugin does not know about
such error and continues sending data to the pipe. It leads to situation:
gprestore breaks reading data of the current relation (for example because
relation does not exist) and starts reading data of the next relation (because
option --on-error-continue is set), but plugin sends data of non-existing
relation.
This patch disables subsets, if the "--on-error-continue" option is set. Also
unit tests were added for function, which checks whether subsets using is
allowed.
Co-authored-by: Dennis Kovalenko <kds@arenadata.io>
```
=> Fix restoring with subset and --on-error-continue together

end_to_end/end_to_end_suite_test.go, restore/data.go, restore/data_test.go
Do not batch replicated tables
When restoring from a larger cluster to a smaller one, tables are [batched](https://github.com/arenadata/gpbackup/blob/76cd98a370dfadf39da8186c92b35f10deeb2a08/restore/data.go#L53-L59) from
several segments onto one. Such batching was [disabled](https://github.com/arenadata/gpbackup/blob/76cd98a370dfadf39da8186c92b35f10deeb2a08/helper/restore_helper.go#L204-L208) on the helper for
replicated tables, but not on the main process. As a result, the main process on
the coordinator launched several copy commands for replicated tables, which,
starting from the second, ended on segments with a missing pipe error. This
error was quietly ignored and could only be seen in the logs on the segments.
This patch disables batching for replicated tables on the coordinator. …
=> ADBDEV-5594: Do not batch replicated tables

helper/backup_helper.go, helper/helper.go, helper/restore_helper.go
Use separate error buffers for different processes in gprestore helper
Problem description:
gprestore helper reused one error buffer for stderr of multiple processes when 
it worked with a plugin. It resulted in the following problem: if the plugin was 
launched several times, the error could be detected only on the 2nd run, while 
the error happens (i.e. plugin outputs something to the stderr) on each plugin 
run. 
Fix:
Add a separate error buffer for each RestoreReader.
As now there is no need for global 'errBuf' variable, it was moved to
'doBackupAgent' as a local variable (keeping it global without obvious need is a
bad practice). For the backup helper case, it is ok to have only one buffer as
only one backup plugin instance is started for each backup helper.
Tests are not added …
=> Use separate error buffers for different processes in gprestore helper

helper/restore_helper.go, integration/helper_test.go, plugins/README.md, plugins/example_plugin.bash
Avoid using stderr to detect plugin failures, wait for plugin processes (#89)
Previously, gpbackup_helper would error out and abort restore operations if any
plugin wrote anything to stderr. Additionally, when using the adb_ddp_plugin to
restore data, gpbackup_helper did not wait for plugin processes, leading to a
large number of zombie processes when restoring with the --resize-cluster flag,
causing the process to stop.
This patch removes the requirement for stderr to be empty. Now, messages
directed to stderr are logged as warnings, allowing the process to continue
without interruption. The helper can still detect when a plugin process has
exited because the exit of a plugin process closes the associated reader
handles, causing an error during subsequent read attempts.
The patch also …
=> Avoid using stderr to detect plugin failures, wait for plugin processes

backup/queries_statistics.go, backup/statistics.go, end_to_end/end_to_end_suite_test.go, integration/statistics_queries_test.go
Store type for statistic as fqdn.
This patch adds storing type for exported statistics as FQDN. Previously if
different schema was used for custom type definition, statistics could not be
restored because type name was used with no explicit schema definition. This
patch adds proper namespace to the type when backup generating restore
statements.
=> Store type for statistic as fqdn.

backup/queries_statistics.go, end_to_end/end_to_end_suite_test.go
Fix backup for empty DB with statistics
`GetAttributeStatistics` and `GetTupleStatistics` did not handle the edge case
of 0 tables, causing gpbackup to fail. This patch adds a check for number of
tables and fixes the issue.
=> ADBDEV-6367: Fix backup for empty DB with statistics

arenadata/Dockerfile, arenadata/README.md
Replace default image for gpbackup tests
This patch replaces the default image for gpbackup tests with full path.
=> ADBDEV-6407: Replace default image for gpbackup tests

backup/data.go, end_to_end/end_to_end_suite_test.go, restore/data.go, restore/data_test.go
1) Make copy command cancelable
If the command used in copy does not support handling of SIGINT signal, then
such copy command cannot be canceled. timeout command does not handle SIGINT
signal by default, so its use in gprestore makes copy command cannot be
canceled until timeout command completes. This patch adds foreground argument
to timeout command so that it can handle SIGINT signal, and thus copy command
can be canceled while timeout command is running.
2) Fix gpbackup/gprestore hanging on fatal error in goroutine
gpbackup/gprestore would hang when a fatal error occurred in goroutine. This
was because fatal error in one goroutine was suppressed, while parallel
goroutines continued running. This patch adds cancel the context when recover
fatal error in goroutine, which causes the …
=> ADBDEV-6613: Fix gpbackup/gprestore hanging on fatal error in goroutine

restore/data.go
Fix pre-creating the required number of pipes in gprestore
Commit 2142387 introduced a problem with pre-creating pipes. gprestore expected
a pipe to be pre-created for each job/copy-queue-size. But the existing logic
was pre-creating pipes for batches of tables instead of the tables themselves.
The main process starts several goroutines, for some of which it does not
pre-create pipes, which leads to a 300-second wait for the pipe to be created
and a subsequent error in restoring the corresponding table. This patch solves
the problem by pre-creating the required number of pipes. The required number
is equal to the multiplication of the number of connections (which is equal to
jobs or copy-queue-size) and the number of batches, because the main process
starts goroutines based on the number …
=> ADBDEV-6893: Fix pre-creating the required number of pipes in gprestore

README.md, arenadata/run_gpbackup_tests.bash
Update gpbackup to support external Orca
Problem:
gpbackup tests require the 'dummy_seclabel' Greenplum contrib module. But, when
setting this module to 'shared_preload_libraries', previous value of 
'shared_preload_libraries' is cleared out. Therefore, in case of GPDB with
external Orca (when Orca is a shared library), Orca is disabled during testing.
As Orca is an essential part of GPDB, testing the gpbackup with disabled Orca is
not correct.
Fix:
In setting of 'shared_preload_libraries', read current value, and add or remove
only 'dummy_seclabel' substring.
Plus, README file is updated with a proper command sample for 'gpconfig'.
--------------------
Steps to reproduce:
```bash
docker build -t gpbackup:test7x -f arenadata/Dockerfile --build-arg …
```
=> Update gpbackup to support external Orca

end_to_end/end_to_end_suite_test.go, utils/agent_remote.go
Cleanup in gprestore kills only own helpers
If several restores of the same backup are launched simultaneously, then the
very first restore that completes during cleanup kills not only its helpers,
but also all helpers working with the same backup, because the processes are
filtered only by same TOC-file. The patch solves the problem by adding a filter
by the name of the pipe, which already has the PID of the main process of the
restore. gpbackup is not affected by this problem, because it will always have
a unique TOC-file.
=> ADBDEV-7175: Cleanup in gprestore kills only own helpers
